### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [tanjim17/BeatAddiction#1]
Can you please tell us what license your app is using? I could find no license info in this repo. Thank in advance!

**Comment by tanjim17** [comment]
I didn't bother to use any in the first place :) Anyway I have added MIT License just now

**Comment by IzzySoft** [comment]
Perfect – thanks! To make it easier to find, install, and keep up with updates of your app, it will [become available here](https://apt.izzysoft.de/fdroid/index/apk/tj.beataddiction) around 19:00 UTC today. Updates will be fetched automatically within 24h of your creating a new tag and attaching an APK to it (provided you keep your tagging pattern as it currently is, i.e. `v<versionName>` :wink:). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from the Readme :smiley:
